spring:
  application:
    name: taskforge-scheduler
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      auto-create: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  shutdown: graceful
taskforge:
  scheduler:
    poll-delay-ms: 1000
