spring:
  application:
    name: taskforge-scheduler
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  shutdown: graceful

